server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          prefer-uri-template: true
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: movie-service
              uri: lb://movie-service
              predicates:
                - Path=/movies/**
            - id: rating-service
              uri: lb://rating-service
              predicates:
                - Path=/ratings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
