spring:
  application:
    name: documentor-service

server:
  port: 18080

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: http://localhost:8013/v3/api-docs
      - name: movie
        url: http://localhost:8011/v3/api-docs
      - name: rating
        url: http://localhost:8012/v3/api-docs

eureka:
  instance:
    prefer-ip-address: true