spring:
  application:
    name: movie-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mmoviedb
    username: postgres
    password: admin

  sql:
    init:
      mode: always
      schema-locations: classpath:/ddl/movie-schema.sql

---
server:
  port: 8011
